import type { Metadata } from "next";
import { Oswald, Raleway } from "next/font/google";
import "./globals.css";
import NavPanel from "./components/NavPanel"
import WorkAvailability from "./components/WorkAvailability";


const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "700"]
})

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`bg-black text-white ${raleway.variable} ${oswald.variable} antialiased`}
>
        {children}
        <NavPanel />
        <WorkAvailability />
      </body>
    </html>
  );
}
